/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    ComponentsGridStack: typeof import('./src/@core/components/ComponentsGridStack.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    Gridstack: typeof import('./src/@core/components/Gridstack.vue')['default']
    GridstackForComponents: typeof import('./src/@core/components/GridstackForComponents.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    VBComponentsGridStack: typeof import('./src/@core/components/VBComponentsGridStack.vue')['default']
  }
}
