// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    ComponentsGridStack: typeof import('./src/@core/components/ComponentsGridStack.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    Gridstack: typeof import('./src/@core/components/Gridstack.vue')['default']
    Gridstack_Copm_Items: typeof import('./src/@core/components/Gridstack_Copm_Items.vue')['default']
    GridstackForComponents: typeof import('./src/@core/components/GridstackForComponents.vue')['default']
    GridstackTorComponents: typeof import('./src/@core/components/GridstackForComponents.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
